### ISSUE TITLE
How to fix syb for GHC 8.2

### ISSUE THREAD

**Issue by RyanGlScott** [dreixel/syb#14]
While testing some packages with GHC 8.2 recently, I noticed that `syb` was broken:

```
src/Data/Generics/Instances.hs:74:10: error:
    • Illegal instance declaration for ‘Data TypeRep’
        (All instance types must be of the form (T t1 ... tn)
         where T is not a synonym.
         Use TypeSynonymInstances if you want to disable this.)
    • In the instance declaration for ‘Data TypeRep’
   |
74 | instance Data TypeRep where
   |          ^^^^^^^^^^^^
```

"Fixing" this issue is a simple matter of applying this patch...

```diff
diff --git a/src/Data/Generics/Instances.hs b/src/Data/Generics/Instances.hs
index 250f049..562ddb1 100644
--- a/src/Data/Generics/Instances.hs
+++ b/src/Data/Generics/Instances.hs
@@ -70,10 +70,12 @@ myMkNoRepType = mkNorepType
 -- Instances of abstract datatypes (6)
 ------------------------------------------------------------------------------
 
+#if __GLASGOW_HASKELL__ < 801
 instance Data TypeRep where
   toConstr _   = error "toConstr"
   gunfold _ _  = error "gunfold"
   dataTypeOf _ = myMkNoRepType "Data.Typeable.TypeRep"
+#endif
 
 
 ------------------------------------------------------------------------------
```

...but I'm not sure if this is how you'd intend to fix it. The problem is that as of GHC 8.2, `TypeRep` doesn't really exist as it used to anymore. The `Type.Reflection` module provides these two datatypes:

```haskell
data TypeRep (a :: k) where ...
data SomeTypeRep where
     SomeTypeRep :: forall k (a :: k). !(TypeRep a) -> SomeTypeRep
```

And in `Data.Typeable`, it provides the following (somewhat backwards-compatible) type synonym:

```haskell
type TypeRep = SomeTypeRep
```

So one option would be replacing the old `Data TypeRep` instance with two new instances on GHC 8.2+ only:

```haskell
instance (Typeable k, Typeable a) => Data (TypeRep (a :: k)) where ...
instance Data SomeTypeRep where ...
```

But to be honest, I really don't know what `syb` is even using that orphan `Data TypeRep` instance for (after all, you can comment it out and `syb` still compiles!), so I don't know if you'd even find the additions worthwhile.

What do you think?

**Comment by dreixel** [comment]
Eh... I don't know. This instance probably made sense when Data and
Typeable were very tied together; not sure we need it now. I'd be ok with
removing it after 8.0.1.

**Comment by alanz** [comment]
FYI, this is an easy way to fix it:

https://github.com/alanz/syb/commit/39f0c153ab208b6066fd5f34f80f85001627ae48

**Comment by RyanGlScott** [comment]
@alanz, I wouldn't consider that a fix, because now `dataTypeOf` yields a result mentioning `"Data.Typeable.TypeRep"`, but in GHC 8.2, `TypeRep` is an alias for `SomeTypeRep`, so really it should mention `"Data.Typeable.SomeTypeRep"` (or ``"Data.Typeable.Internal.SomeTypeRep"`, if you want to be pedantic).

But since @dreixel has indicated that he isn't inclined to keep that orphan instance around, I propose we just use CPP to not define it on GHC 8.2 and later. #15 accomplishes this.
