### ISSUE TITLE
homepage is dead

### ISSUE THREAD

**Issue by MangoIV** [dreixel/syb#43]
Hi, I just wanted to tell you that your homepage seems to be dead.

**Comment by sergv** [comment]
Thanks, that's unfortunate but probably not entirely unforeseen. The old hompage is still available in the internet wayback machine. I've fixed it so the next release's homepage will point to github unless someone suggests a better alternative.

**Comment by MangoIV** [comment]
You can point to the link of the wayback machine?

**Comment by sergv** [comment]
@MangoIV http://wayback.archive.org/

**Comment by MangoIV** [comment]
Nah because you asked for "other suggestions" you could like your old homepage but in the wayback machine :)

**Comment by sergv** [comment]
I don't think linking old homepage in the wayback machine is a good idea. I had no control over old homepage and with wayback machine will have even less. The old homepage poses historical interest, but discussions of 6.10 base split are hardly relevant today.

**Comment by MangoIV** [comment]
sure, this was just a suggestion, I don't know what the old homepage contains. Thank you for your help. :)
