### ISSUE TITLE
CI broken for GHC 7.x

### ISSUE THREAD

**Issue by andreasabel** [dreixel/syb#44]
@sergv I noticed that GHC 7 is no longer covered by CI since GitHub removed the `ubuntu-18.04` runners. https://github.com/dreixel/syb/actions/runs/5039493753

The `haskell-ci` generated CIs do still handle GHC 7 because they use an image.

Maybe a solution would be that you restore the auto-generated Haskell CI but keep your hand-modified CI as a second CI so that you can test macOS etc.

**Comment by sergv** [comment]
It seems supporting GHCs that cannot be installed with ghcup is like swimming against the current. I think those CI's were due to be removed for some time already and Github's removal of `ubuntu-18.04` runners is the ultimate clue to actually remove them.
