### ISSUE TITLE
CI: remove old header, maybe rename to something else than `haskell-ci`?

### ISSUE THREAD

**Issue by andreasabel** [dreixel/syb#46]
Since CI is now hand-generated and no longer produced by `haskell-ci`, the header is confusing:
https://github.com/dreixel/syb/blob/54431aa7801bd905140bf2e7844c11b9029e9ef6/.github/workflows/haskell-ci.yml#L1-L15
Suggestion: remove the comment and rename the workflow to something other than `haskell-ci.yml`.

**Comment by sergv** [comment]
Good idea to remove the comment. Regarding renaming `haskell-ci.yml` I don't know - do you think it may cause some confusion?

**Comment by andreasabel** [comment]
I confuses me, at least, since I assume that `haskell-ci.yml` has been generated by Haskell CI.
If you were to write a CI from a blank slate, you would probably name it more naturally `ci.yml`, `build.yml`, `test.yml` ...
