### ISSUE TITLE
Function `ext2` has been added 13 years ago, but is not exported.

### ISSUE THREAD

**Issue by BinderDavid** [dreixel/syb#51]
The function `ext1` from the module `Data.Generic.Aliases` has a twin `ext2` for binary type constructors which was added ~13 years ago. Sadly, someone forgot to also add it to the export list of the module :) This is almost certainly an oversight.

**Comment by sergv** [comment]
Released as `0.7.2.4` along with documentation improvements. Thanks for bringing it all up.
